name: Vite Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build
    steps:
      - name: Deploy Artificat
        id: deployment
        uses: actions/deploy-pages@v1
